import logging

import httpx

from config.settings import settings
from orchestrator.diff_utils import build_line_index
from orchestrator.parser import Finding, extract_verdict, parse_findings

logger = logging.getLogger(__name__)

_GH_API = "https://api.github.com"
_HEADERS = {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}


def _auth() -> dict:
    return {"Authorization": f"Bearer {settings.github_token}"}


def post_review(
    repo_full_name: str,
    pr_number: int,
    commit_sha: str,
    results: dict[str, str],
    pr_files,
) -> None:
    line_index = build_line_index(pr_files)
    verdicts: dict[str, str] = {}
    inline_comments: list[dict] = []
    overflow_findings: list[str] = []

    for agent_name, output in results.items():
        verdicts[agent_name] = extract_verdict(output)
        findings = parse_findings(output)

        for f in findings:
            comment_body = f"**[{agent_name.capitalize()}] {f.title}**\n\n{f.body}"
            if (
                f.file
                and f.line
                and f.file in line_index
                and f.line in line_index[f.file]
            ):
                inline_comments.append(
                    {
                        "path": f.file,
                        "line": f.line,
                        "side": "RIGHT",
                        "body": comment_body,
                    }
                )
            else:
                overflow_findings.append(comment_body)

    overall = (
        "BLOCK"
        if "BLOCK" in verdicts.values()
        else ("WARN" if "WARN" in verdicts.values() else "PASS")
    )
    event = "COMMENT"
    badge_color = {"PASS": "green", "WARN": "yellow", "BLOCK": "red"}[overall]

    summary_rows = "\n".join(
        f"| {k.capitalize()} | {v} |" for k, v in verdicts.items()
    )
    overflow_section = (
        ("\n\n---\n\n**Additional findings (not tied to a specific line):**\n\n"
         + "\n\n---\n\n".join(overflow_findings))
        if overflow_findings
        else ""
    )
    review_body = (
        f"## AI Code Review — {repo_full_name}#{pr_number}\n\n"
        f"![{overall}](https://img.shields.io/badge/review-{overall}-{badge_color})\n\n"
        f"| Agent | Verdict |\n|---|---|\n{summary_rows}"
        f"{overflow_section}\n\n---\n*Generated by AI Code Review Pipeline*"
    )

    payload = {
        "commit_id": commit_sha,
        "body": review_body,
        "event": event,
        "comments": inline_comments,
    }

    url = f"{_GH_API}/repos/{repo_full_name}/pulls/{pr_number}/reviews"
    with httpx.Client(timeout=30) as client:
        r = client.post(url, json=payload, headers={**_HEADERS, **_auth()})
        if r.status_code not in (200, 201):
            logger.error("GitHub review API error %d: %s", r.status_code, r.text)
            r.raise_for_status()

    logger.info(
        "Posted review on %s#%d — %d inline, %d overflow, verdict=%s",
        repo_full_name, pr_number, len(inline_comments), len(overflow_findings), overall,
    )
